language: generic

script:
- npm install -g gitbook-cli
- rm -rf out
- gitbook init out
- gitbook build out
deploy:
  local_dir: out
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master